name: Deploy

on:
  push:
    branches:
      - master

jobs:
  list-files:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files in Repository
        run: ls -al