name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t hayrat.io/scrum-poker:latest .

      - name: Remove Existing Container
        run: |
          if [ "$(docker ps -aq -f name=hayrat_scrum_poker)" ]; then
            docker rm -f hayrat_scrum_poker
          fi
#
#      - name: Remove Old Images
#        run: |
#          docker image prune -f

      - name: Run New Container
        run: |
          docker run -d \
          --name hayrat_scrum_poker \
          -p 3131:80 \
          hayrat.io/scrum-poker:latest